### ISSUE TITLE
Overlay port not cached

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#10]
I'm forced to use a custom overlay port of Lua 5.1 (vcpkg only supports 5.3 and I have a large ecosystem based on 5.1), and it looks like the action does not cache it. Here's how I use the action:

```
- name: Install dependencies with vcpkg
  uses: lukka/run-vcpkg@v1
  with:
    vcpkgArguments: '@${{env.vcpkgResponseFile}}'
    vcpkgDirectory: '${{github.workspace}}/3rdparty/vcpkg'
```

Here's how the output looks like:

```
Computing installation plan...
The following packages are already installed:
    boost-graph[core]:x64-osx
    hunspell[core]:x64-osx
    pugixml[core]:x64-osx
    yajl[core]:x64-osx
The following packages will be built and installed:
    lua[core]:x64-osx -- /Users/runner/runners/2.168.0/work/Mudlet/Mudlet/3rdparty/our-vcpkg-dependencies/lua
Package yajl:x64-osx is already installed
Package hunspell:x64-osx is already installed
Package boost-graph:x64-osx is already installed
Package pugixml:x64-osx is already installed
Starting package 1/1: lua:x64-osx
Building package lua[core]:x64-osx...
-- Installing port from location: /Users/runner/runners/2.168.0/work/Mudlet/Mudlet/3rdparty/our-vcpkg-dependencies/lua
-- Downloading https://www.lua.org/ftp/lua-5.1.5.tar.gz...
```

The action is in https://github.com/vadi2/Mudlet/blob/add-macos-action-ci/.github/workflows/build-mudlet.yml.
