### ISSUE TITLE
Unable to simple install dependencies as before

### ISSUE THREAD

**Issue by Shatur** [lukka/run-vcpkg#107]
Here is what I trying:

```yml
      - name: Install vcpkg packages
        uses: lukka/run-vcpkg@v10
        with:
          runVcpkgInstall: true
          runVcpkgFormatString: '[`install`, `--clean-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`, `tesseract[cpu-independed]`, `ecm`, `qt5-svg`, `qt5-multimedia`, `qt5-winextras`, `qt5-tools`]'
          vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092

```

Here is the error I get:

```
run-vcpkg action execution failed: Cannot run 'install,--clean-after-build,--x-install-root,D:/a/crow-translate/b/vcpkg_installed,--triplet,x64-windows,tesseract[cpu-independed],ecm,qt5-svg,qt5-multimedia,qt5-winextras,qt5-tools' because no valid directory has been provided.
```

I would expect to have a workflow as with v7.
