### ISSUE TITLE
vcpkg with nuget binary packages

### ISSUE THREAD

**Issue by kmrashad** [lukka/run-vcpkg#121]
Hello Lukka,
Do you know how to get nuget packages (created from vcpkg export ..) when using run-vcpkg ?
I want to use it for big libraries like Qt which is not possible to compile on CI

**Comment by lukka** [comment]
@kmrashad for the Nuget Package scenario I believe the `run-vcpkg` should just be used as a way to restore vcpkg from cache (i.e. its executable and its needed data files), and then follow [the `vcpkg`'s instructions](https://vcpkg.io/en/docs/users/binarycaching.html#github-packages) to start it up in a subsequent step, e.g.,

```yml
   - name: Setup vcpkg (do not install any package)
     uses: lukka/run-vcpkg@v10
   - name: 'Setup NuGet Credentials'
     [...] # Follow the example from vcpkg docs about using Nuget packages.
```
