### ISSUE TITLE
Using vcpkg with binary sources

### ISSUE THREAD

**Issue by kmrashad** [lukka/run-vcpkg#122]
I have to use VCPKG_BINARY_SOURCES to store a big library. According to binary caching documentation from vcpkg, It is working for me locally. I can restore packages on my windows. But using run-vcpkg on Github Actions, it does not restore packages. I had copied my vcpkg cache from local build machine and extracted it to `files` location given in VCPKG_BINARY_SOURCES environment variable. 

Given that,
1. vcpkg is used as a submodule
2. Previous vcpkg cache is copied to binsrc directory before running run-vcpkg

```
jobs:

    env:
        VCPKG_DEFAULT_TRIPLET: x64-windows
        VCPKG_BINARY_SOURCES: 'clear;files,${{ github.workspace }}/binsrc,readwrite'
```

Any ideas on why packages are restored ?
