### ISSUE TITLE
Setting doNotCacheOnWorkflowFailure: true disables caching entirely (?)

### ISSUE THREAD

**Issue by equeim** [lukka/run-vcpkg#125]
I use run-vcpkg action from my own compisite action like this: https://github.com/equeim/action-setup-vcpkg-msvc/blob/master/action.yml

There I set doNotCacheOnWorkflowFailure input to true. Then, when job is completed successfully, post action from run-vcpkg says that:
```
Save vcpkg and its artifacts into GitHub service cache
  Caching is disabled, saving cache is skipped.
```
AFAIK, it can happen only if doNotCache input is true and it false by default.

There is log when run-vcpkg is invoked:
```
Run lukka/run-vcpkg@v10
  with:
    vcpkgGitCommitId: dd42206f86a7b9f7747ccb63fa0e36baaab5fa1e
    appendedCacheKey: d817028e1760c31609f9e53637b20f8ddde03229611a26d440364f0eceb7219e
    doNotCacheOnWorkflowFailure: true
    vcpkgDirectory: D:\a\libtremotesf\libtremotesf/vcpkg
    runVcpkgInstall: false
    vcpkgGitURL: https://github.com/microsoft/vcpkg.git
    doNotUpdateVcpkg: false
    doNotCache: false
    vcpkgJsonGlob: **/vcpkg.json
    vcpkgJsonIgnores: ['**/vcpkg/**']
    runVcpkgFormatString: [`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]
    useShell: true
    logCollectionRegExps: \s*"(.+CMakeOutput\.log)"\.\s*;\s*"(.+CMakeError\.log)"\.\s*;\s*(.+out\.log)\s*;\s+(.+err\.log)\s*;\s*(.+vcpkg.+\.log)\s*
    jobStatus: success
```

Could it be related to the fact that I use it from composite action?
