### ISSUE TITLE
How to control where the downloaded files go?

### ISSUE THREAD

**Issue by pmeems** [lukka/run-vcpkg#130]
I've got this yml for Github Actions: https://github.com/MapWindow/MapWinGIS/blob/feature/GDAL3-VS2019/.github/workflows/msbuild.yml
I use this snippet:
```
      uses: lukka/run-vcpkg@v10.1
      with:
        runVcpkgInstall: true
        vcpkgDirectory:  ${{ github.workspace }}/src/vcpkg
        runVcpkgFormatString: "[`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]"
```

How do I control where the files are saved?
My application expects the files to be in `src\vcpkg_installed\x86-windows\include` as referenced in my msbuild project file as `$(ProjectDir)\vcpkg_installed\$(VcpkgTriplet)\include`

I tried using `--x-install-root` but couldn't get it to work. The slashes in `${{ github.workspace }}` where removed.

Please advice.

**Comment by pmeems** [comment]
Thanks for the quick reply.

When I use this code snippet:
```
    - name: run-vcpkg
      # You may pin to the exact commit or the version.
      # uses: lukka/run-vcpkg@c5ce6a7de6e5ce834a25f7d55b6c250a275a6732
      uses: lukka/run-vcpkg@v10.1
      with:
        runVcpkgInstall: true
        vcpkgDirectory:  ${{ github.workspace }}/src/vcpkg
        runVcpkgFormatString: "[`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.GITHUB_WORKSPACE]/src/vcpkg_installed`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]"
```
It resolves in `Running 'vcpkg install,--recurse,--clean-after-build,--x-install-root,D:aMapWinGISMapWinGIS/src/vcpkg_installed,--triplet,x64-windows' in directory 'D:\a\MapWinGIS\MapWinGIS\src'` Notice the missing slashes.

I now use `VCPKG_INSTALLED_DIR: ${{ github.workspace }}\src\vcpkg_installed\` in my `env` block and
```
    - name: run-vcpkg
      # You may pin to the exact commit or the version.
      # uses: lukka/run-vcpkg@c5ce6a7de6e5ce834a25f7d55b6c250a275a6732
      uses: lukka/run-vcpkg@v10.1
      with:
        runVcpkgInstall: true
        vcpkgDirectory:  ${{ github.workspace }}\src\vcpkg\
        runVcpkgFormatString: "[`install`, `--recurse`, `--clean-after-build`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]"
```
I also added `$(ProjectDir)\vcpkg_installed\$(VCPKG_DEFAULT_TRIPLET)\include` to my `Additional Include Directories` of my MSBuild project file and now all is working.

Thanks for providing the action and the provided help.
