### ISSUE TITLE
Installing completely broken with current vcpkg

### ISSUE THREAD

**Issue by rhuijben** [lukka/run-vcpkg#136]
Also opening an issue here, as it appears this action is now broken against current vcpkg master on `windows-latest` and `windows-2019`.

vcpkg tries to extract 7zip, using 7zip as it somehow can't find `tar.exe` in `windows\system32`.

I'm looking for some temporary workaround, and some help escallating this issue with the Microsoft vcpkg project as it is slowing development on projects relying on vcpkg builds that need updates of their dependencies.

See https://github.com/microsoft/vcpkg/issues/23448

**Comment by rhuijben** [comment]
```
A suitable version of 7zip was not found (required v21.7.0).
Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> D:\a\SharpProj\SharpProj\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\archives.cpp(101)
```

**Comment by rhuijben** [comment]
```
    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 5a8a1dfff8e2dffd4c8cc2d1fc0da379ffd18b25

    - name: Ensure Proj packages are available
      run: vcpkg.exe install "tiff[core]:x64-windows-static-md" "proj[core,tiff]:x64-windows-static-md" "tiff[core]:x86-windows-static-md" "proj[core,tiff]:x86-windows-static-md"
```
