### ISSUE TITLE
Saving duplicate cache

### ISSUE THREAD

**Issue by Mher594** [lukka/run-vcpkg#184]
I've noticed that sometimes when opening pull requests the GitHub action does the build and writes to cache successfully, but then when merging the branch the action does not use the cache. I was thinking that maybe the OS was updated and changed, but that's not the case as in the image bellow shows. 

![duplicate_cache](https://user-images.githubusercontent.com/4984553/224930906-e9a86991-c129-4f73-aab5-084fc6273760.jpg)

I was wondering is it expected behavior or am I missing something? Bellow is the action
```
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-tests:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows-release
            build-type: Release
          - os: ubuntu-latest
            triplet: x64-linux-release
            build-type: Release
          - os: macos-latest
            triplet: x64-osx-release
            build-type: Release

    steps:     
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"

      - name: Configure CMake
        run: |
          cmake -S . -B make -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
      - name: Build
        working-directory: ./make
        run: |
          cmake --build . --config ${{ matrix.build-type }} --parallel $(nproc)
```
