### ISSUE TITLE
Error: EACCES: permission denied, mkdir when running with act on full 

### ISSUE THREAD

**Issue by eladm-ultrawis** [lukka/run-vcpkg#213]
I have trying to run the following workflow with act:

```
name: ci2
run-name: PR Check run by ${{ github.actor }}

on:
  workflow_dispatch: # allow manual runs 
jobs:
  linux-clang:
    # runs-on: ubuntu-22.04
    runs-on: ubuntu-latest
    steps:
    - name: get vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '9f03078bdcbab3ad8c1e3927c40c3fb48e42501f'
         # This is the default location of the directory containing vcpkg sources.
         # Change it to the right location if needed.
         # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
```

When I run it on ubuntu-22.04 it succeeds. however if I use the act latest and full image it fails:

```
act -j linux-clang -P ubuntu-latest=catthehacker/ubuntu:full-latest
```

output:

```
i2/linux-clang]   ❓  ::group::Prepare output directories
| The vpckg root directory: '/home/eladm/workspace/cranebit/vcpkg'
[ci2/linux-clang]   ❓  ::endgroup::
| ⏱ elapsed: 0.002 seconds
| Error: EACCES: permission denied, mkdir '/home/eladm/workspace/b'
[ci2/linux-clang]   ❗  ::error::run-vcpkg action execution failed: EACCES: permission denied, mkdir '/home/eladm/workspace/b'
[ci2/linux-clang]   ❌  Failure - Main get vcpkg
[ci2/linux-clang] exitcode '24': failure
[ci2/linux-clang] 🏁  Job failed
Error: Job 'linux-clang' failed
```

here is a link to the issue on the act repo:

[https://github.com/nektos/act/issues/2086](https://github.com/nektos/act/issues/2086)
