### ISSUE TITLE
"You must provide a value expression following the '/' operator."

### ISSUE THREAD

**Issue by ffissore** [lukka/run-vcpkg#22]
When trying to install gtk on windows using the following step, I got the error mentioned above
```yaml
  windows_build:
    runs-on: windows-latest
    steps:
      # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
      - name: Restore from cache and install vcpkg
        # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v3
        with:
          setupOnly: true
          vcpkgGitCommitId: c7ab9d3110813979a873b2dbac630a9ab79850dc
      - run: |
          $VCPKG_ROOT/vcpkg install gtk:x64-windows
```
This ^ is how it's written [in the docs](https://github.com/lukka/run-vcpkg#setup-vcpkg-only)

Workaround was to change the `run` part like this
```yaml
  windows_build:
    runs-on: windows-latest
    steps:
      # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
      - name: Restore from cache and install vcpkg
        # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v3
        with:
          setupOnly: true
          vcpkgGitCommitId: c7ab9d3110813979a873b2dbac630a9ab79850dc
      - run: |
          ${{ env.VCPKG_ROOT }}\vcpkg install gtk:x64-windows
```
