### ISSUE TITLE
Cache action needs update to newer version

### ISSUE THREAD

**Issue by tooomm** [lukka/run-vcpkg#243]
Since April 15th, the old cache is gone and the used cache actions needs to be bumped from v3 to v4:
`Warning: Failed to restore: Cache service responded with 422`

https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/

**Comment by lukka** [comment]
@tooomm could you please confirm that `run-vcpkg@dev/cache-v4` is working for you?

**Comment by tooomm** [comment]
Hmmm, using
```
     - name: Run vcpkg
        uses: lukka/run-vcpkg@dev/cache-v4
        with:
          runVcpkgInstall: true
          doNotCache: false
        env:
          VCPKG_DEFAULT_TRIPLET: 'x64-windows'
          VCPKG_DISABLE_METRICS: 1
```
in the workflow file downloads correctly I think:
`Download action repository 'lukka/run-vcpkg@dev/cache-v4' (SHA:30387331141cd078977e3cc6f436ad5a2d93cf7d)`
but still gives `Warning: Failed to restore: Cache service responded with 422`

And at the end of the step shows:
```
...
Failed to save: Unable to reserve cache with key runnerOS=win2220250406.1.0-vcpkgGitCommit=c63619856b89f0af4d77ba2049396039e4985418, another job may be creating this cache.  
More details: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset  
⏱ elapsed: 7.810 seconds  
run-vcpkg action execution succeeded
```

Rerunning the job does not change the situation.
