### ISSUE TITLE
Binary caching fails due to curl timeout

### ISSUE THREAD

**Issue by chrismile** [lukka/run-vcpkg#248]
Hi,

I've been using run-vcpkg successfully for a long time now for binary caching. Example usage:

```
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitURL: 'https://github.com/microsoft/vcpkg.git'
        vcpkgGitCommitId: '9b75e789ece3f942159b8500584e35aafe3979ff'
```

... but yesterday and today, I get a lot of errors like this:

```
Waiting for 90 remaining binary cache submissions...
curl: warning: failed with exit code 28
Completed submission of boost-cmake:x64-linux-release-only@1.87.0 to 0 binary cache(s) in 2.3 min (1/90)
curl: warning: failed with exit code 28
Completed submission of boost-headers:x64-linux-release-only@1.87.0 to 0 binary cache(s) in 2.3 min (2/90)
curl: warning: failed with exit code 28
Completed submission of boost-config:x64-linux-release-only@1.87.0 to 0 binary cache(s) in 2.3 min (3/90)
curl: warning: failed with exit code 28
...
```

This happens until the GitHub actions runner times out due to running for 6 hours.
An example for this can be found in this run: https://github.com/chrismile/sgl/actions/runs/15283529924/job/42988123292

Curl error 28 seems to indicate a timeout. Is this rather an issue on the run-vcpkg or GitHub side?
