### ISSUE TITLE
Cache key doesn't seem to include triplet

### ISSUE THREAD

**Issue by PazerOP** [lukka/run-vcpkg#27]
I haven't done extensive testing to verify this is the case, but it seems to me that the cache key doesn't take the value of `vcpkgTriplet` into account. Given the following:

```
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v3.0
      with:
        vcpkgGitCommitId: 7192d3affa4b1d8f88e3e730eb561612c24f7d78
        vcpkgArguments: 'SDL2 openSSL glbinding cpp-httplib libzippp cppcoro'
        vcpkgTriplet: ${{ matrix.triplet }}
```

If I have `x86-windows` and `x64-windows` in my matrix, it *seems* like they both try to save under the same cache key. This means that every time the workflow is triggered, one of them gets rebuilt, since they are stepping on each other. I added `appendedCacheKey: "42-pazer-${{ matrix.triplet }}"` and it seemed to resolve the issue.
