### ISSUE TITLE
VC package was not installed properly

### ISSUE THREAD

**Issue by aleksas** [lukka/run-vcpkg#38]
**[SANDBOX REPOSITORY](https://github.com/aleksas/FooBar)** : [Failed RUN](https://github.com/aleksas/FooBar/runs/1031434124?check_suite_focus=true)

During VS2019 solution build via msbuild build crashes with following error:
`fatal error C1083: Cannot open include file: 'curl/curl.h': No such file or directory`

Below are config files:

---
**.github/workflows/main.yml**
```yaml
name: Win32Sample GitHub Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v3
        with:
          vcpkgArguments: '@${{ github.workspace }}/build/vcpkg.txt'
          vcpkgTriplet: 'x86-windows'
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
          vcpkgGitCommitId: '8a9a97315aefb3f8bc5d81bf66ca0025938b9c91'
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      - name: Build Binary
        shell: cmd
        run: call .\build\build.cmd
```
---
**build\build.cmd**
```batch
@echo off
pushd "%~dp0..\"

if exist Debug rd /s /q Debug
if exist Release rd /s /q Release
if exist x64 rd /s /q x64

"%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release /p:Platform=x86

:exit
popd
@echo on
```
---
**build/vcpkg.txt**
```
curl[tool]
jsoncpp
```
---
**workflow log**
```sh
  Run lukka/get-cmake@latest29s
  Cache not found for input keys: 315670198.
Run lukka/get-cmake@latest
Restore from cache
  Cache not found for input keys: 315670198.
Download and extract CMake
  C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\6c8ce093-1657-4c05-9da4-70d0617028e5', 'D:\a\_temp\315670198')"
Add CMake to PATH
get-cmake action execution succeeded
  Restore from cache and run vcpkg7m 12s
  
Run lukka/run-vcpkg@v3
  with:
    vcpkgArguments: @D:\a\FooBar\FooBar/build/vcpkg.txt
    vcpkgTriplet: x86-windows
    vcpkgDirectory: D:\a\FooBar/vcpkg
    vcpkgGitCommitId: 8a9a97315aefb3f8bc5d81bf66ca0025938b9c91
    setupOnly: false
    vcpkgArtifactIgnoreEntries: !.git
  **/*
  !installed
  !/vcpkg
  !vcpkg.exe
  !vcpkgArtifactIgnoreEntries
  
    vcpkgGitURL: https://github.com/microsoft/vcpkg.git
    cleanAfterBuild: true
    doNotUpdateVcpkg: false
    useShell: true
    doNotCache: false
Restore vcpkg and its artifacts from cache
  Cache's key = 'localGitId=-879632411-args=1980734528-os=1553167195-appendedKey=42-triplet=-755526354'.
  Running restore-cache
  Cache miss.
Set output env vars
  Set task output variable 'RUNVCPKG_VCPKG_ROOT_OUT' to value: D:\a\FooBar\vcpkg
tool: C:\Program Files\Git\bin\git.exe
Fetching the commit id at D:\a\FooBar\vcpkg
fatal: not a git repository (or any of the parent directories): .git
Check whether vcpkg repository is up to date

 Build Binary3s
    RUNVCPKG_VCPKG_TRIPLET_OUT: x86-windows
Project "D:\a\FooBar\FooBar\FooBar.sln" (1) is building "D:\a\FooBar\FooBar\source\FooBar.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\".
  Creating directory "D:\a\FooBar\FooBar\Release\".
  Creating directory "Release\foo_.0dd6d879.tlog\".
InitializeBuildStatus:
  Creating "Release\foo_.0dd6d879.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\CL.exe /c /ID:\a\FooBar\FooBar\\include /Zi /nologo /W3 /WX- /diagnostics:column /sdl /O2 /Oi /Oy- /GL /D _CRT_SECURE_NO_WARNINGS /D WIN32 /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Release\\" /Fd"Release\vc142.pdb" /Gd /TP /analyze- /FC /errorReport:queue foo_bar.cc
  foo_bar.cc
D:\a\FooBar\FooBar\source\foo_bar.cc(8,10): fatal error C1083: Cannot open include file: 'curl/curl.h': No such file or directory [D:\a\FooBar\FooBar\source\FooBar.vcxproj]
Done Building Project "D:\a\FooBar\FooBar\source\FooBar.vcxproj" (default targets) -- FAILED.
Done Building Project "D:\a\FooBar\FooBar\FooBar.sln" (default targets) -- FAILED.

Build FAILED.

"D:\a\FooBar\FooBar\FooBar.sln" (default target) (1) ->
"D:\a\FooBar\FooBar\source\FooBar.vcxproj" (default target) (2) ->
(ClCompile target) -> 
  D:\a\FooBar\FooBar\source\foo_bar.cc(8,10): fatal error C1083: Cannot open include file: 'curl/curl.h': No such file or directory [D:\a\FooBar\FooBar\source\FooBar.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.41
##[error]Process completed with exit code 1.
```
