### ISSUE TITLE
manifest not supported ?

### ISSUE THREAD

**Issue by Milerius** [lukka/run-vcpkg#53]
<img width="1273" alt="Capture d’écran 2020-11-07 à 10 20 09" src="https://user-images.githubusercontent.com/21139416/98437504-e2850c00-20e2-11eb-9078-7fcaa9ff15e0.png">

```yml
- name: vcpkg deps (Linux)
        if: runner.os == 'Linux'
        env: # Or as an environment variable
          CXXFLAGS: -stdlib=libc++
          LDFLAGS: -stdlib=libc++
          CXX: clang++-10
          CC: clang-10
        uses: KomodoPlatform/run-vcpkg@v5
        with:
          vcpkgArguments: '--feature-flags=binarycaching,manifests --x-manifest-root=${{ github.workspace }} --overlay-ports=${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-custom-ports/ports --x-install-root=${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-repo/installed'
          vcpkgDirectory: '${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-repo'
          appendedCacheKey: ${{ hashFiles('vcpkg.json') }}

      - name: vcpkg deps (MacOS)
        if: runner.os == 'macOS'
        env: # Or as an environment variable
          CXX: /usr/local/opt/llvm@9/bin/clang++
          CC: /usr/local/opt/llvm@9/bin/clang
        uses: KomodoPlatform/run-vcpkg@v5
        with:
          vcpkgArguments: '--feature-flags=binarycaching,manifests --x-manifest-root=${{ github.workspace }} --overlay-ports=${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-custom-ports/ports --x-install-root=${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-repo/installed'
          vcpkgDirectory: '${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-repo'
          appendedCacheKey: ${{ hashFiles('vcpkg.json') }}

      - name: vcpkg deps (Windows)
        if: runner.os == 'Windows'
        uses: KomodoPlatform/run-vcpkg@v5
        with:
          vcpkgArguments: '--feature-flags=binarycaching,manifests --x-manifest-root=${{ github.workspace }} --overlay-ports=${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-custom-ports/ports --x-install-root=${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-repo/installed --triplet=x64-Windows'
          vcpkgDirectory: '${{ github.workspace }}/ci_tools_atomic_dex/vcpkg-repo'
          appendedCacheKey: ${{ hashFiles('vcpkg.json') }}
```

It's seems that manifest are not handle properly, and vcpkg remove arguments are bypassed but correctly forwarded for install:

```bash
Running 'vcpkg install --recurse --feature-flags=binarycaching,manifests --x-manifest-root=D:\a\atomicDEX-Desktop\atomicDEX-Desktop --overlay-ports=D:\a\atomicDEX-Desktop\atomicDEX-Desktop/ci_tools_atomic_dex/vcpkg-custom-ports/ports --x-install-root=D:\a\atomicDEX-Desktop\atomicDEX-Desktop/ci_tools_atomic_dex/vcpkg-repo/installed --triplet=x64-Windows --clean-after-build' in directory 'D:\a\atomicDEX-Desktop\atomicDEX-Desktop\ci_tools_atomic_dex\vcpkg-repo' ...
```

vcpkg.json:

```json
{
  "name": "atomicdex-desktop",
  "version-string": "0.3.0",
  "dependencies": [
    "entt",
    "folly",
    "boost-multiprecision",
    "boost-random",
    "boost-lockfree",
    "boost-stacktrace",
    "doctest",
    "fmt",
    "nlohmann-json",
    "range-v3",
    "libsodium",
    "spdlog",
    "date",
    "cpprestsdk",
    "cpp-taskflow"
  ]
}
```

https://vcpkg.readthedocs.io/en/stable/specifications/manifests/#manifests-vcpkgjson
