### ISSUE TITLE
file COPY cannot read symlink

### ISSUE THREAD

**Issue by alex-taffe** [lukka/run-vcpkg#84]
I’m not really sure if this is an issue with CMake, vcpkg, or `run-vcpkg` but it isn’t happening locally, so I’m guessing the latter. When trying to install `libusb`, I get the error:

```
CMake Error at scripts/cmake/vcpkg_install_msbuild.cmake:160 (file):
    file COPY cannot read symlink
    "D:/a/AutoML/AutoML/vcpkg/buildtrees/libusb/src/3ae1ed06fa-f8218372d8.clean/README"
    to duplicate at
    "D:/a/AutoML/AutoML/vcpkg/buildtrees/libusb/x64-windows-rel/3ae1ed06fa-f8218372d8.clean/README":
    No such file or directory.
  Call Stack (most recent call first):
    ports/libusb/portfile.cmake:42 (vcpkg_install_msbuild)
    scripts/ports.cmake:79 (include)

  Error: Building package libusb:x64-windows failed with: BUILD_FAILED
```

My vcpkg.txt is:
```
--triplet
x64-windows
libwebsockets
libusb
```

My GitHub action is using `windows-latest` and the step for vcpkg is:
```
    - name: Install vcpkg
      uses: lukka/run-vcpkg@v7
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'
        appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
```
The vcpkg submodule is on `2020.07`. Some people were saying they were having this issue with OneDrive (https://github.com/Microsoft/vcpkg/issues/2488) but seeing as this library is doubtful to use OneDrive, I’m not sure. I can’t reproduce locally so I’m not sure what’s going on
