### ISSUE TITLE
upload vcpkg buid logs as GitHub Actions artifacts

### ISSUE THREAD

**Issue by Be-ing** [lukka/run-vcpkg#96]
This would make it convenient to debug build failures of vcpkg ports.

**Comment by lukka** [comment]
The build logs are already dumped in the ordinary output log of the workflow, see the `logCollectionRegExps` input. It is extremely useful as it allows you to use RegExp and identify any file path, and contextually dump it into the output log.

I see that you may want to have an archive attached to the workflow as an generated artifact. That is easy to accomplish, by looking into the current source code for the above mentioned input. Contributions are welcome!

**Comment by Be-ing** [comment]
This can easily be done with another action but it would be nice to have it done automatically by run-vcpkg.

```

    - name: Upload GitHub Actions artifact of vcpkg build logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.os }}
        path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
```
